#Database used: MySQL5.6 with SQL Fiddle.

CREATE TABLE ENROLLMENT(SID INTEGER NOT NULL, 
ClassName VARCHAR(20) NOT NULL,
GRADE CHAR(1) NOT NULL);

INSERT INTO ENROLLMENT VALUES(123, "Processing", 'A');
INSERT INTO ENROLLMENT VALUES(123, "Python", 'B');
INSERT INTO ENROLLMENT VALUES(123, "Scratch", 'B');
INSERT INTO ENROLLMENT VALUES(662, "Java", 'B');
INSERT INTO ENROLLMENT VALUES(662, "Python", 'A');
INSERT INTO ENROLLMENT VALUES(662, "JavaScript", 'A');
INSERT INTO ENROLLMENT VALUES(662, "Scratch", 'B');
INSERT INTO ENROLLMENT VALUES(345, "Scratch", 'A');
INSERT INTO ENROLLMENT VALUES(345, "JavaScript", 'B');
INSERT INTO ENROLLMENT VALUES(345, "Python", 'A');
INSERT INTO ENROLLMENT VALUES(555, "Python", 'B');
INSERT INTO ENROLLMENT VALUES(555, "JavaScript",'B');

SELECT ClassName,COUNT(*) AS Total FROM ENROLLMENT GROUP BY ClassName ORDER BY Total DESC;