-- Database used: SQLite(WebSQL) with SQL Fiddle.

CREATE TABLE STEM(NAME VARCHAR(10) NOT NULL,
ADDRESS VARCHAR(8) NOT NULL,
ID INTEGER NOT NULL,
SameFam INTEGER,
PRIMARY KEY(ID)
);

INSERT INTO STEM VALUES("ALICE","A",10,NULL);
INSERT INTO STEM VALUES("BOB","B",15,NULL);
INSERT INTO STEM VALUES("CARMEN","C",22,NULL);
INSERT INTO STEM VALUES("DIEGO","A",9,10);
INSERT INTO STEM VALUES("ELLA","B",3,15);
INSERT INTO STEM VALUES("FARKHAD","D",11,NULL);

DELETE from STEM where SameFam is NULL and EXISTS(SELECT ID FROM STEM S2
WHERE S2.SameFam = Stem.ID);

